import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Header from '../components/Header'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div className="body flex flex-col items-center justify-center ">
      <Head>
        <title>Khushaal Choithramani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
    </div>
  )
}
